pipeline{
    agent any
    stages{
        stage("Pull image"){
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'DOCKERHUB_USERNAME', passwordVariable: 'DOCKERHUB_PASSWORD')]) {
                    sh 'docker pull $DOCKERHUB_USERNAME/basic-email-sharer:1.0'
                }
            }
        }
        stage("Run basic-email-sharer"){
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'DOCKERHUB_USERNAME', passwordVariable: 'DOCKERHUB_PASSWORD')]) {
                    sh 'docker run --name basic-email-sharer -p 8090:8080 $DOCKERHUB_USERNAME/basic-email-sharer:1.0'
                }
            }
        }
    }
}